# Generated by Django 3.1.5 on 2021-02-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('fullname', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('existed_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'communication',
            },
        ),
    ]
